require "knoxcall/errors"
require "knoxcall/ulid"
require "knoxcall/warnings"
require "knoxcall/bootstrap"
require "knoxcall/credentials_file"
require "knoxcall/dpop"
require "knoxcall/client"
require "knoxcall/bound_route"
require "knoxcall/signup"
require "knoxcall/token_exchange"
require "knoxcall/workload_provider"
require "knoxcall/login"
require "knoxcall/wrap_transport"
require "knoxcall/intercept_resolver"
require "knoxcall/intercept_store"
require "knoxcall/egress_observations"
require "knoxcall/intercept_pipeline"
require "knoxcall/resources/unwraps_envelope"
require "knoxcall/resources/routes"
require "knoxcall/resources/secrets"
require "knoxcall/resources/webhooks"
require "knoxcall/resources/workflows"
require "knoxcall/resources/clients"
require "knoxcall/resources/oauth_clients"
require "knoxcall/resources/environments"
require "knoxcall/resources/api_keys"
require "knoxcall/resources/roles"
require "knoxcall/resources/account"
require "knoxcall/resources/audit_logs"
require "knoxcall/resources/logs"
require "knoxcall/resources/agents"
require "knoxcall/resources/crypto"
require "knoxcall/resources/pki"
require "knoxcall/resources/vaults"
require "knoxcall/resources/dynamic_db"
require "knoxcall/resources/ai_gateway"
require "knoxcall/resources/wrap"
require "knoxcall/resources/opportunities"

module KnoxCall
  VERSION = "1.1.0"
  SDK_VERSION = "knoxcall-ruby/#{VERSION}"
  DEFAULT_API_BASE = "https://api.knoxcall.com"
  DEFAULT_CLOUD_HOST = "knoxcall.com"
end
